### ISSUE TITLE
401 error from IndieAuth

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#1]
I'm consistently getting a 401 error when trying to log in using monocle.p3k.io.

- I log in with http://microsub-dev.jackjamieson.net/
- Monocle redirects to the IndieAuth screen, where I click 'authorize'
- I'm redirected back to monocle.p3k.io, which returns an error dump:

```
Array
(
    [code] => 401
    [header] => HTTP/1.1 401 Unauthorized
Server: nginx/1.14.0
Date: Mon, 02 Jul 2018 16:47:32 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
X-Robots-Tag: noindex
Link: ; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Vary: Accept-Encoding
X-Endurance-Cache-Level: 2
    [body] => {"code":"indieauth.user_not_found","message":"User Not Found on this Site","data":{"status":"401","response":"http:\/\/microsub-dev.jackjamieson.net\/"}}
    [error] => 
    [error_description] => 
    [url] => http://microsub-dev.jackjamieson.net/wp-json/microsub/endpoint?action=channels
    [debug] => HTTP/1.1 401 Unauthorized
Server: nginx/1.14.0
Date: Mon, 02 Jul 2018 16:47:32 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
X-Robots-Tag: noindex
Link: ; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Vary: Accept-Encoding
X-Endurance-Cache-Level: 2

{"code":"indieauth.user_not_found","message":"User Not Found on this Site","data":{"status":"401","response":"http:\/\/microsub-dev.jackjamieson.net\/"}}
    [headers] => Array
        (
            [Server] => nginx/1.14.0
            [Date] => Mon, 02 Jul 2018 16:47:32 GMT
            [Content-Type] => application/json; charset=UTF-8
            [Transfer-Encoding] => chunked
            [Connection] => keep-alive
            [Expires] => Wed, 11 Jan 1984 05:00:00 GMT
            [Cache-Control] => no-cache, must-revalidate, max-age=0
            [X-Robots-Tag] => noindex
            [Link] => ; rel="https://api.w.org/"
            [X-Content-Type-Options] => nosniff
            [Access-Control-Expose-Headers] => X-WP-Total, X-WP-TotalPages
            [Access-Control-Allow-Headers] => Authorization, Content-Type
            [Vary] => Accept-Encoding
            [X-Endurance-Cache-Level] => 2
        )

    [rels] => Array
        (
            [https://api.w.org/] => Array
                (
                    [0] => http://microsub-dev.jackjamieson.net/wp-json/
                )

        )

)

```

**Comment by jackjamieson2** [comment]
Further information, get_current_user_id() always returns 0 when called on [line 77 of class-microsub-endpoint.php: ](
https://github.com/jackjamieson2/yarns-microsub-server/blob/master/includes/class-microsub-endpoint.php#L77)

**Comment by jackjamieson2** [comment]
@dshanke If you have time, would you mind taking a look?  My instinct is that there is an error on my end rather than IndieAuth.  (I can log into quill with the Micropub plugin)

**Comment by jackjamieson2** [comment]
@dshanske If you have time, would you mind taking a look?

I can log in to Quill with the Micropub plugin, so I think this is an error with my code here, rather than a problem with IndieAuth.  If you can see a problem, I'd appreciate your help. I'll keep trying to work through this in the meantime

**Comment by jackjamieson2** [comment]
https://github.com/jackjamieson2/yarns-microsub-server/commit/a3a502d779e72557cd237ddc38feade75d7fcd9e adds a fallback to use indieauth.com if the indieauth plugin is not installed. Begins to address this issue (by providing a workaround)

**Comment by dshanske** [comment]
I am rewriting the Micropub code right now, I may learn how to address this as I am digging into its Indieauth code.

**Comment by jackjamieson2** [comment]
Thank you!  In the meantime I'm falling back to using indieauth.com and
that's working fine for development

**Comment by dshanske** [comment]
A new release of the IndieAuth plugin just occurred that might solve this problem.

**Comment by jackjamieson2** [comment]
I just tested and was able to log in to microsub clients with the IndieAuth plugin enabled, so I think this is fixed thanks to @dshanske
