### ISSUE TITLE
Escaped HTML / JS leaks into item text

### ISSUE THREAD

**Issue by bekopharm** [jackjamieson2/yarns-microsub-server#104]
While most of my feeds look fine and do no longer inject HTML I've various feeds that show escaped HTML or JS in feed items that should not be there:

Examples:

## Leaked HTML that should not be there
```html
<div class="if-your-feed-reader-displays-this-then-it-is-violating-the-Atom-spec-RFC-4287-section-4.2.14"></div>
```
![gnome-shell-screenshot-KCGNK0](https://user-images.githubusercontent.com/5016428/81690552-bc482180-945b-11ea-9d53-abfa799372dd.png)

## Leaked JSON-LD data
```json
{"@context":"http://schema.org","@type":"Review","author": [...]
```

![gnome-shell-screenshot-FEOOK0](https://user-images.githubusercontent.com/5016428/81690698-f7e2eb80-945b-11ea-997c-ef832f3b1369.png)

## HTML Entities
```text
Nach einem &quot;Computerangriff von außen&quot; 
```
![gnome-shell-screenshot-TIXLK0](https://user-images.githubusercontent.com/5016428/81690983-645dea80-945c-11ea-99a9-46c70ee50973.png)

```text
Facebook Launches &#039;Discover,&#039; A Secure Proxy
```
![gnome-shell-screenshot-UXOKK0](https://user-images.githubusercontent.com/5016428/81691163-ad15a380-945c-11ea-9d57-94752bc2fbaa.png)

Both readers I use, Monocle and Indigenous for Android, look the same on this.

May be related to #74 and #15 

Preview (RSS and ATOM) is also affected:
![gnome-shell-screenshot-TEWEK0](https://user-images.githubusercontent.com/5016428/81691796-b5baa980-945d-11ea-9482-3d14c100ffc7.png)

Feeds look fine in regular feed readers, like `Liferea`

**Comment by dshanske** [comment]
@bekopharm I may take this over at github.com/dshanske/parse-this and see about better filtering. @jackjamieson2 hasn't updated to the latest version of Parse This, which actually does something with  JSON-LD, so not sure if I already fixed some of this, but I can check if you provide the URLs for the feed.

**Comment by bekopharm** [comment]
Huh, so I did manage to bark up the wrong tree again :confused: 

I'll compile a list @dshanske  :+1:

**Comment by jackjamieson2** [comment]
Thanks @bekopharm and @dshanske. I’m quite behind on yarns updates, sorry for that! @dshanske let me know if you resolve this in parse this and I’ll push a new version.

**Comment by dshanske** [comment]
@jackjamieson2 Hope you are staying safe. I did a major update on Parse This to add JSON-LD and other options a few weeks back, but I intend to return to add docblocks and will likely do some code cleanup then.

**Comment by jackjamieson2** [comment]
@dshanske Safe here, thanks! Even without COVID-19 I'd be staying home to write right now, so things aren't too bad for me. Mostly just buried in writing, which is why I haven't been active on development stuff or IRC.  Hope you're staying safe too.

**Comment by dshanske** [comment]
@bekopharm I've been exploring this, and it is an upstream issue. SimplePie is stripping the script tags...so that is why my code isn't.

**Comment by dshanske** [comment]
I'm disabling SimplePie's stripping in favor of my own.

**Comment by dshanske** [comment]
Resolved with refresh of Parse This library
