### ISSUE TITLE
Remove IndieAuth Code from this Plugin and Make IndieAuth Plugin a Dependency

### ISSUE THREAD

**Issue by dshanske** [jackjamieson2/yarns-microsub-server#105]
https://github.com/indieweb/wordpress-micropub/issues/226

Suggesting the same thing in Micropub. For one, we'd like to stop promoting indieauth.com as the developer is not maintaining it, and promote the self-hosted option.

**Comment by jackjamieson2** [comment]
In fact, at some point my code broke the IndieAuth.com support so I've already made the IndieAuth plugin a dependency. But I think the old IndieAuth.com code is still in there and I should remove it
