### ISSUE TITLE
Make dshanske an approved contributor to this project

### ISSUE THREAD

**Issue by dshanske** [jackjamieson2/yarns-microsub-server#108]
I want to help, while you are busy. Volunteering to do some fixes, if you want to give me privileges.

**Comment by jackjamieson2** [comment]
Thanks @dshanske 

I just added you

All good here, though it has been difficult to find time to catch myself back up on this lately

**Comment by dshanske** [comment]
@jackjamieson2 Hope we'll get a chance to talk soon.

**Comment by jackjamieson2** [comment]
I'd like that! I'll send you an email
