### ISSUE TITLE
SimplePie Dependency

### ISSUE THREAD

**Issue by dshanske** [jackjamieson2/yarns-microsub-server#113]
I've removed SimplePie as part of Parse This. SimplePie was added to Parse This solely for Yarns, due issues with it not being updated. Post Kinds never bundled the code. WordPress updated to SimplePie 1.5.3 in WP5.5, and later to 1.5.6 to add PHP8.0 support.

When this plugin(Yarns) was sent to the repository, the bundling of SimplePie was questioned. The minimum version requirement for Yarns is 4.7. Suggest it either be bumped to 5.5. This does mean anyone who froze updates before Gutenberg may have an issue, but it makes it worthy of discussion.

@jackjamieson2 Would like your input on this one. I can also move the dependency into Yarns itself.

**Comment by jackjamieson2** [comment]
I think it's reasonable to bump the requirement. 

Another possibility is to keep support for older versions of WordPress, but only for h-feeds.  So RSS support could be unlocked based on one's WordPress version (which could be communicated with a nag notice)

**Comment by dshanske** [comment]
Merged
