### ISSUE TITLE
Fatal Error: Call to undefined function current_date() 

### ISSUE THREAD

**Issue by shawfactor** [jackjamieson2/yarns-microsub-server#114]
Error here: caught Error: Call to undefined function current_date() in ******/wp-content/plugins/yarns-microsub-server-master/includes/class-yarns-microsub-aggregator.php:309

AFAICT current_date is not a php function it is a mysql function. In any case why not use ne of the wordpress functions for this.

**Comment by dshanske** [comment]
The WordPress function is current_datetime
