### ISSUE TITLE
Search for RSS feeds directly

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#23]
When adding a feed, if the user searches for an rss feed directly (e.g. searches for https://www.thestar.com/feeds.articlestopstories.rss instead of simply https://www.thestar.com/), it doesn't work.

This is because the search function checks for feeds on the page, but does not recognize rss feeds themselves. 

An easy thing to fix, just add a check if the URL itself is an rss/atom/xml feed, and if so return it directly

**Comment by jackjamieson2** [comment]
Since I switched from file_get_contents to wp_remote_get, I should be able to do this easily by simply getting the `header-> content-type` .  See https://codex.wordpress.org/Function_Reference/wp_remote_post

**Comment by dshanske** [comment]
Actually, Parse This already does this detection if you want me to add a return

**Comment by jackjamieson2** [comment]
To update this with some additional detail

Parse-This currently returns a parsed feed if an rss (or similar) URL is entered directly.

e.g. 
``` 
$search = new Parse_This( "http://jackjamieson.net/feed/);
return $search->fetch_feeds();
```
The above code returns the following:
```
{
  "results": [
    {
      "type": "feed",
      "_feed_type": "RSS",
      "name": "Jack Jamieson",
      "url": "https:\\/\\/jackjamieson.net\\/",
      "items": [
      ...
      ... (and so on)
```

This means that searching for `http://jackjamieson.net/feed/` returns that there is an RSS feed at `http://jackjamieson.net/`

---
This might be the expected behavior, since Parse-This is returning the URL from <channel><link>

If that's the case, then I can modify Yarns to identify whether a parsed feed was returned, in which case the returned URL should be overwritten with the original URL that was queried: 

e.g.  Something like:
```
// $url already contains "http://jackjamieson.net/feed/"
$search = new Parse_This($url );

$feeds = $search->fetch_feeds();

-  if $feeds contains nested items, it means a parsed feed was returned
-  $feeds['results'][0]['url'] = $url // set the correct URL

return $feeds;
```

I worry that this solution is a bit clumsy, but I think it would work

**Comment by dshanske** [comment]
It is fixed now in Parse This.

**Comment by jackjamieson2** [comment]
Thanks!
