### ISSUE TITLE
Endpoint problem when Micropub plugin is installed and IndieAuth plugin is not

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#30]
I recently realized I had set up my endpoint incorrectly (see #29).  That is now fixed, but I have two other problems now

## IndieAuth error
With IndieAuth 3.1.6 or 3.1.8 installed, I see the following error when I access an endpoint URL (e.g. /wp-json/yarns-microsub/1.0/endpoint?action=channels)

> <b>Notice</b>: Undefined variable: this in <b>/.../wp-content/plugins/wordpress-indieauth-master/includes/class-indieauth-debug.php</b> on line <b>79</b><br />

This error prepends the normal return value, which is a json formatted list of channels. 

## Micropub error
If I disable IndieAuth altogether, and leave Micropub 1.4.3 enabled, it seems like Micropub hijacks my endpoint. 

For example, when I access an endpoint URL (e.g. /wp-json/yarns-microsub/1.0/endpoint?action=channels) I get a 401 error and my log says: 
> "**Micropub** Error: 401 unauthorized - missing access token"

If I disable Micropub, this error goes away and the endpoint correctly returns a list of channels.  (For testing purposes, the endpoint is set up to bypass authorization)

## Conclusion
Downgrading IndieAuth to 3.1.5 fixes both issues.  Given that the latest versions of both IndieAuth and Micropub seem to play nice with other plugins, I think this can be fixed in Yarns, but I'm having trouble diagnosing this.

Paging @dshanske in case you have any ideas

**Comment by pfefferle** [comment]
can you re-try it with version 3.1.9 https://github.com/indieweb/wordpress-indieauth/releases/tag/3.1.9

**Comment by jackjamieson2** [comment]
Thanks @pfefferle! With IndieAuth 3.1.9 installed, everything works great.

Note to self: The second issue noted here: that Micropub's authorization hijacks the Microsub endpoint only when IndieAuth is not installed, remains a problem.

**Comment by dshanske** [comment]
Did you try it with Micropub 2.0?

**Comment by jackjamieson2** [comment]
Amazing!  I didn't realize there had so much work since 1.4.3 in the WordPress repository.  

Installing Micropub 2.0 from Github fixed this.

Thank you @dshanske!

**Comment by dshanske** [comment]
You inspired the work by what you said at the Summit.
