### ISSUE TITLE
Integrating new parse-this

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#36]
@dshanske  - Could you help me with this when you have time?

It's likely this is my fault in Yarns, since I'm having some trouble conceptualizing exactly how Yarns will integrate with parse-this (As @dshanske noted before, I was calling individual subfiles in parse-this rather than just using the Parse_This class itself.   - https://chat.indieweb.org/wordpress/2018-11-14#t1542220258477400)

In the `parse-this-update` branch (https://github.com/jackjamieson2/yarns-microsub-server/tree/parse-this-update) I've edited the `Yarns_Microsub_Parser::parse_feed` function to:
```
public static function parse_feed( $url, $count = 20 ) {
		if ( ! $url ) {
			return;
		}
		$parse = new Parse_This( $url );
		$parse->fetch();
		$parse->parse();
		return $parse->get();
		
	}
```

Previously this function fetched the url with wp_remote_get(), then attempted to parse its content as an h-feed, and failing that as an rss-feed.

New version attempts to offload all of that to parse-this.  I'm not sure I have this quite right, so let me know if I should change my code.

As an example, here is the return value with url = http://aaronparecki.com

```
<br />
<b>Strict Standards</b>:  Only variables should be passed by reference in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>264</b><br />
{"checkin":{"type":"card","name":"John Deere Financial","url":"https:\/\/foursquare.com\/v\/4d79173ba56e3704426d7667","location":"Johnston, Iowa","latitude":"41.674398","longitude":"-93.739428"},"photo":"http:\/\/aaronparecki.com\/2018\/11\/15\/7\/photo.jpg","syndication":"https:\/\/www.swarmapp.com\/user\/59164\/checkin\/5bed85275d891b002c7323c9","location":{"type":"adr","latitude":"41.674398","longitude":"-93.739428","locality":"Johnston","region":"IA","country":"United States"},"type":"entry","url":"https:\/\/aaronparecki.com\/2018\/11\/15\/7\/","name":"at John Deere Financial","published":"2018-11-15T08:39:35-06:00","updated":"2018-11-15T08:39:35-06:00","author":{"type":"card","name":null,"url":"http:\/\/aaronparecki.com\/","photo":null},"post-type":"checkin"}
```

Two issues here:

1) Strict standards message - This is triggered by `$parse->fetch();`

2) Only the first item from Aaron's h-feed is returned

I think this is basically my issue, but I'm hoping @dshanske might be able to offer some advice

**Comment by jackjamieson2** [comment]
Making progress!  The new feed argument for parse seems to be doing the trick.

A few new observations.

## 1. Strict Standards message

The strict standards message still occurs after I updated parse-this today. (now it's on line 276 of class-parse-this.php)
```
$content_type = trim( array_shift( explode( ';', $content_type ) ) );
```

Based on a stackoverflow thread I tried replacing this  temporary variables, which looks ugly but quiets the error:

```
$tmp1 = explode( ';', $content_type );
$tmp2 = array_shift( $tmp1 );
$content_type = trim ($tmp2);
```

## 2. New php notices parsing http://aaronparecki.com

When I parse aaronparecki.com, parse-this returns two notices before the feed:

<br />
<b>Notice</b>:  Undefined index: host in <b>/home4/karmaco1/public_html/microsub-dev/wp-includes/class-http.php</b> on line <b>912</b><br />
<br />
<b>Notice</b>:  Undefined index: url in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this-html.php</b> on line <b>458</b><br />

(After those notices, the feed seems to be parsed correctly)

## 3. Complicated feed structure at tantek.com
When I parse http://tantek.com the returned json is very complicated since the actual feed of entries is nested deeply in `items -> 0 -> items`

Yarns handles this in the function  `Yarns_Microsub_Parser::locate_hfeed()` — tantek's site was among the most complicated to get that working for




## Reference
For reference, I'm calling parse-this with the following function:
```
	public static function parse_feed( $url, $count = 20 ) {
		// Currently $count does nothing, but it should limit the size of the returned feed

		if ( ! $url ) {
			return;
		}
		$args = array(
			'alternate' => false,
			'feed'      => true,
		);
		
		$parse = new Parse_This( $url );
		$parse->fetch();
		$parse->parse($args);
		return $parse->get();
		
	}
```

**Comment by jackjamieson2** [comment]
Some updates (tested with newest parse-this from packagist as of Nov 21)

## 1  -- Author.php is missing from Simplepie 

Fixed this on my end with a composer update, so I think Parse-This just needs a dependencies update pushed to GitHub

## 2 class-parse-this-mf2.php
<b>Warning</b>:  trim() expects parameter 1 to be string, array given in <b>/.../public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this-mf2.php</b> on line <b>1117</b><br />

*My line number is slightly off because I was troubleshooting the file.  The offending line is `$content = trim( static::get_plaintext( $mf, 'content' ) );`

This error occured when parsing the following feeds: 
https://jacky.wtf/feeds/articles.xml
https://www.torontowolfpack.com/feed/

## 3 class-parse-this-html.php
```
<b>Notice</b>:  Undefined index: url in <b>/.../public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this-html.php</b> on line <b>459</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /.../public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this-html.php:459) in <b>/home4/karmaco1/public_html/microsub-dev/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
```

This error occured when parsing the following feeds:
- https://islandinthenet.com/
- http://aaronparecki.com//syndicated

My line numbers are slightly off because i was troubleshooting.  The offending line is `$jf2['publication'] = preg_replace( '/^www\./', '', wp_parse_url( $jf2['url'], PHP_URL_HOST ) );`

Can be fixed by only running that line if url is set.  But that's a bandaid at best
```
if ( isset( $jf2['url'])){
	$jf2['publication'] = preg_replace( '/^www\./', '', wp_parse_url( $jf2['url'], PHP_URL_HOST ) );`
}
```

**Comment by jackjamieson2** [comment]
Thanks @dshanske — All of the issues I noticed above are now resolved.

I noticed two more php notices that occurs on some sites.  Testing a few sites more or less at random and found errors when searching for feeds at https://indieweb.org and at https://islandinthenet.com.


Both examples were found using Yarns' search function, which calls Parse-This using the following:
```
$search = new Parse_This( $url );
return $search->fetch_feeds();
```

Returned data with php notices is below:

https://indieweb.org
```
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php:215) in <b>/home4/karmaco1/public_html/microsub-dev/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
{"results":[{"url":"http:\/\/indieweb.org\/wiki\/index.php?title=Main_Page&printable=yes","type":"feed","name":"Printable version of this page [p]"},{"url":"http:\/\/indieweb.org\/wiki\/index.php?title=Special:RecentChanges&feed=atom","type":"atom","name":"IndieWeb Atom feed"}]}
```
https://islandinthenet.com

```
<br />
<b>Notice</b>:  Undefined index: type in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>194</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php:194) in <b>/home4/karmaco1/public_html/microsub-dev/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
{"results":[{"url":"https:\/\/islandinthenet.com\/wp-json\/oembed\/1.0\/embed?url=https%3A%2F%2Fislandinthenet.com%2F","type":"feed","name":""},{"url":"https:\/\/islandinthenet.com\/wp-json\/oembed\/1.0\/embed?url=https%3A%2F%2Fislandinthenet.com%2F&format=xml","type":"feed","name":""},{"url":"https:\/\/islandinthenet.com\/feed\/","type":"rss","name":"Island in the Net \u00bb Feed"},{"url":"https:\/\/islandinthenet.com\/comments\/feed\/","type":"rss","name":"Island in the Net \u00bb Comments Feed"},{"url":"https:\/\/islandinthenet.com\/about\/feed\/","type":"rss","name":"Island in the Net \u00bb About Comments Feed"}]}
```

**Comment by dshanske** [comment]
I made some modifications. It now does not display types it doesn't know about. Although I did have some debate as to whether it should show mf2 and jf2 json rel-alternates.

**Comment by jackjamieson2** [comment]
At this point, Yarns relies wholly on Parse-This for searching and parsing, and this seems to be working well.  There are some minor issues (e.g. #23 ) but these are probably best left for other threads, so I'm closing this issue. 

If I notice any new parse-this errors etc. then I will create issues on the [Parse-This repo](https://github.com/dshanske/parse-this/)
