### ISSUE TITLE
Final testing for beta release

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#50]
Although everything was working fine on my staging server, when I updated Yarns on my live site it seems to be broken.

The Microsub client displays the channels and list of feeds for each channel, but does not display feed content.

Not sure what the problem is, but I'd like to figure this out asap

**Comment by dshanske** [comment]
I tried it out and it won't let me add any new feeds.

**Comment by jackjamieson2** [comment]
Hmmm, 

I think this is a compatibility error with parse-this in post-kinds, since I'm seeing a php error:

03-Jan-2019 16:13:49 America/Toronto] PHP Fatal error:  Cannot redeclare post_type_discovery() (previously declared in /.../wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/functions.php:211) in /.../wp-content/plugins/yarns-microsub-server-master/vendor/parse-this/includes/functions.php on line 211

**Comment by dshanske** [comment]
It was a typo. Fixed in the Parse This library. It ensures that the global function can't be redeclared. It said post_type_discover instead of discovery

**Comment by jackjamieson2** [comment]
That seemed to fix the issue viewing and adding feeds, thanks @dshanske!

Remaining issues:

### Yarns
Some of my channels are not displaying timelines properly (tested in Monocle and Together).  Since others are working, I'll need to examine each timeline's JSON to figure out what happened

### Parse-this
*I'll compile a list of parse-this issues as I discover them, just noting this for now*
- In feed for david.shanske.com/all, Author information is not parsed. 


### To do
I've been thinking that a faster and clearer debugging viewer would be useful.  

So, I'm going to create a debugger viewable in the admin area. This will display the raw JSON for a few types of requests:
- Search (for finding feeds on a page)
- Preview (preview feed at a URL)
- Channels - display a list of channels
- Timeline - display timeline for a given feed

This should help speed up the debugging process (particularly for resolving the Yarns issue above)

**Comment by jackjamieson2** [comment]
Just added some debugging tools as of 6a4676d6568e379c9ea543035a70cedfd4e30da6 (Version 0.1.1 beta)

### Added debugging options
Now the admin screen includes a log all requests from clients, as well as responses for:
- results from parsing
- results from searching for feeds
- returning list of channels
- returning timeline for a channel
- deleting a feed from a channel

Additionally, I have added buttons to the bottom of the admin screen:
1. delete posts from all channels
2. force poll (Normally sites are only polled if a specified amount of time has passed since the previous poll attempt, force polling ignores this requirement)


### Previous issues with timeline:
I wrote above that feed content was not being displayed once I installed Yarns on my live site.  The problem was that the channels had been created before I added the option to filter channels by post-type (#22).  As a result, the channels did not have a list of allowed post-types, and so displayed nothing.  Since I'm the only one who's been using Yarns so far, I just deleted my old channels and created new ones. Works great
