### ISSUE TITLE
Brainstorming: Display documentation/tutorial for brand new (empty) servers

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#51]
For channels that (a) have no feeds or (b) have feeds but no posts for some reason, they are likely to display as blank with no explanation in most clients.

It would be simple and helpful to generate a dummy feed item explaining either
- "This channel does not yet have any feeds"
- "This channel's feeds do not have any posts"

Not a high priority, but should be pretty simple

**Comment by dshanske** [comment]
Isn't that a client not a server issue?

**Comment by jackjamieson2** [comment]
I see what you mean, and yes I agree.

Having thought about this a bit more, though, I think this might be a good opportunity to present a brief tutorial, though maybe focus on brand new servers with no channels set up yet.

Brainstorming: 
- If no channels are set up, then return a 'Getting started' channel.
- Getting started channel can have a post (or posts) explaining how to add channels, feeds etc.  This could include a link to the Yarns admin page in the user's WordPress dashboard

- Rationale: For people who are unfamiliar with microsub, the separation of client and server could be confusing.  Since some clients offer the ability to modify channels & subscriptions, the server can sit basically completely in the background.  However, other clients don't have these features, so channel management has to be done within the server itself.  

So I'll leave this open for now.  Still low priority, but I think this might be a good way to present documentation.  See #37

**Comment by jackjamieson2** [comment]
Although I still think an interactive tutorial would be nice, it would be a lot of work to implement. Text documentation and a video tutorial can do almost as well, and are much simpler to implement.
