### ISSUE TITLE
PHP warning for timezone

### ISSUE THREAD

**Issue by asuh** [jackjamieson2/yarns-microsub-server#55]
I curiously installed this repo to my localhost and upon activation I get the following PHP warning:
`Notice: date_default_timezone_set(): Timezone ID '' is invalid in /www/[...]/plugins/yarns-microsub-server/yarns-microsub.php on line 75`

It's accompanied by another warning:
`Warning: Cannot modify header information - headers already sent by (output started at /www/[...]/plugins/yarns-microsub-server/yarns-microsub.php:75) in /www/[...]/wp-admin/includes/misc.php on line 1126`

I'm running PHP 7.1.x with WordPress 4.9.8.

**Comment by jackjamieson2** [comment]
Thanks asuh - I'll check it out

**Comment by jackjamieson2** [comment]
This is referring to line 75 in yarns-microsub.php
```
date_default_timezone_set( get_option( 'timezone_string' ) );
```
On my system, this returns the timezone from my WordPress settings, which is "America/Toronto"

I guess this setting is empty on your system.

I added this line when I was adding a feature to log the last time each feed was polled. The idea was to use the same time format as the wordpress setting.  However, I suspect this may not be necessary. 

So, I'm going to see how things work with that line removed altogether.  If that doesn't work, I'll figure out a better method.  I should avoid using date_default_timezone_set anyway
