### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by dshanske** [jackjamieson2/yarns-microsub-server#56]
Notice: Undefined variable: channels in /wp-content/plugins/yarns-microsub-server/includes/class-yarns-microsub-channels.php on line 38

Warning: Invalid argument supplied for foreach() in /wp-content/plugins/yarns-microsub-server/includes/class-yarns-microsub-admin.php on line 163

Got this on a new install.

**Comment by jackjamieson2** [comment]
Thanks - I'll check it out this week
