### ISSUE TITLE
Bug: 401 unauthorized

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#59]
A significant bug - Yarns' endpoint seems to be consistently returning a 401 unauthorized error.

see : https://chat.indieweb.org/wordpress/2019-03-31#t1554055384815200

I tried rolling back to previous version of Yarns and the error persists, so maybe an interaction between Yarns and indieauth, or some other issue.

Since Yarns' auth code is based on an old version of Micropub anyway, this is a good opportunity to update it. So that's my next step

The endpoint response according to Monocle.p3k.io
```
{
    "code": 401,
    "header": "HTTP/1.1 401 Unauthorized\r\nServer: nginx/1.14.1\r\nDate: Sun, 31 Mar 2019 18:39:26 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nExpires: Wed, 11 Jan 1984 05:00:00 GMT\r\nCache-Control: no-cache, must-revalidate, max-age=0\r\nX-Robots-Tag: noindex\r\nLink: <https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"\r\nX-Content-Type-Options: nosniff\r\nAccess-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages\r\nAccess-Control-Allow-Headers: Authorization, Content-Type",
    "body": "Unauthorized",
    "error": "",
    "error_description": "",
    "url": "https://microsub-dev.jackjamieson.net/wp-json/yarns-microsub/1.0/endpoint?action=channels",
    "debug": "HTTP/1.1 401 Unauthorized\r\nServer: nginx/1.14.1\r\nDate: Sun, 31 Mar 2019 18:39:26 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nExpires: Wed, 11 Jan 1984 05:00:00 GMT\r\nCache-Control: no-cache, must-revalidate, max-age=0\r\nX-Robots-Tag: noindex\r\nLink: <https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"\r\nX-Content-Type-Options: nosniff\r\nAccess-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages\r\nAccess-Control-Allow-Headers: Authorization, Content-Type\r\n\r\n\"Unauthorized\"",
    "headers": {
        "Server": "nginx/1.14.1",
        "Date": "Sun, 31 Mar 2019 18:39:26 GMT",
        "Content-Type": "application/json",
        "Transfer-Encoding": "chunked",
        "Connection": "keep-alive",
        "Expires": "Wed, 11 Jan 1984 05:00:00 GMT",
        "Cache-Control": "no-cache, must-revalidate, max-age=0",
        "X-Robots-Tag": "noindex",
        "Link": "<https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"",
        "X-Content-Type-Options": "nosniff",
        "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages",
        "Access-Control-Allow-Headers": "Authorization, Content-Type"
    },
    "rels": {
        "https://api.w.org/": [
            "https://microsub-dev.jackjamieson.net/wp-json/"
        ]
    }
}
```

**Comment by jackjamieson2** [comment]
Been chipping away at this problem a bit. No solution yet but I suspect that the plugin function load order is incorrect.  If Yarns' plugin functions are executed too early, then they try to get user information for authentication before WordPress has determined the active user. 

(Offline, not yet committed) I've started restructuring Yarns to use a similar authorization/endpoint structure as the current version of indieweb/wordpress-micropub.  Even after getting my code to match Micropub's quite closely, I'm getting an error.  (In the new code, it's a 403 error, but this is a reflection of the new code structure rather than evidence that the cause of the error itself changed). 

So, next steps are to try and figure out what is different between my the Micropub plugin and my code.  Will spend some time on this tomorrow.  Hopefully I'll solve the issue, otherwise I'll attempt to perform a clearer diagnosis and ask for suggestions

**Comment by jackjamieson2** [comment]
Created a branch while I try to figure this out: https://github.com/jackjamieson2/yarns-microsub-server/tree/auth-update

**Comment by jackjamieson2** [comment]
Took an additional pass as this today:

Since authorization is working in https://github.com/indieweb/wordpress-micropub, and Yarns' auth was based on an older version of that plugin, I've used that as a base to get auth working again.

1) I overwrote the auth-update testing branch with files from wordpress-micropub
2) Did a find and replace to avoid conflicts micropub:
    - micropub -> microsub
    - mp_get -> ms_get
3) Prevented conflicts with micropub plugin
    - functions.php -> prevent conflict with is_assoc_array function 
4) Changed endpoint address from 'microsub/1.0/endpoint' to 'yarns-microsub/1.0/endpoint'
5) Added some logging to determine where auth fails
    - endpoint.php -> load_auth() lines 96-100  -- https://github.com/jackjamieson2/yarns-microsub-server/blob/auth-update/includes/class-microsub-endpoint.php#L96
    - Added to the 403 error output. It now includes the $microsub_auth_response and $scopes variables.  

**Results:** 
When logging into monocle, a 403 unauthorized error is returned. 

Full error is included at the bottom of this message. The relevant part is: `"error_description": "Unauthorized : [][]"`

This indicates two things:
1. The error is returned from line 99 in endpoint.php
    ```
    if ( ! current_user_can( 'read' ) ) {
	    return new WP_Error( 'forbidden', 'Unauthorized : ' . $logs , array( 'status' => 403 ) );
    }
    ```
2. `static::$microsub_auth_response` and `static::$scopes` are both empty.  (They are the two empty json arrays in the error description: [][])


  Stuck for now, so will ask for help.  Auth works in the micropub plugin, and my simple method of replacing micropub to microsub has not worked.  Some of my Yarns files remain in the directory, but they aren't included or required anywhere, so should be dormant. 





Full error from Monocle:
```
{
    "code": 403,
    "header": "HTTP/1.1 403 Forbidden\r\nServer: nginx/1.14.1\r\nDate: Tue, 16 Apr 2019 17:17:53 GMT\r\nContent-Type: application/json; charset=UTF-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nExpires: Wed, 11 Jan 1984 05:00:00 GMT\r\nCache-Control: no-cache, must-revalidate, max-age=0\r\nX-Robots-Tag: noindex\r\nLink: <https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"\r\nX-Content-Type-Options: nosniff\r\nAccess-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages\r\nAccess-Control-Allow-Headers: Authorization, Content-Type",
    "body": {
        "error": "forbidden",
        "error_description": "Unauthorized : [][]"
    },
    "error": "",
    "error_description": "",
    "url": "https://microsub-dev.jackjamieson.net/wp-json/microsub/1.0/endpoint?action=channels",
    "debug": "HTTP/1.1 403 Forbidden\r\nServer: nginx/1.14.1\r\nDate: Tue, 16 Apr 2019 17:17:53 GMT\r\nContent-Type: application/json; charset=UTF-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nExpires: Wed, 11 Jan 1984 05:00:00 GMT\r\nCache-Control: no-cache, must-revalidate, max-age=0\r\nX-Robots-Tag: noindex\r\nLink: <https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"\r\nX-Content-Type-Options: nosniff\r\nAccess-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages\r\nAccess-Control-Allow-Headers: Authorization, Content-Type\r\n\r\n{\"error\":\"forbidden\",\"error_description\":\"Unauthorized : [][]\"}",
    "headers": {
        "Server": "nginx/1.14.1",
        "Date": "Tue, 16 Apr 2019 17:17:53 GMT",
        "Content-Type": "application/json; charset=UTF-8",
        "Transfer-Encoding": "chunked",
        "Connection": "keep-alive",
        "Expires": "Wed, 11 Jan 1984 05:00:00 GMT",
        "Cache-Control": "no-cache, must-revalidate, max-age=0",
        "X-Robots-Tag": "noindex",
        "Link": "<https://microsub-dev.jackjamieson.net/wp-json/>; rel=\"https://api.w.org/\"",
        "X-Content-Type-Options": "nosniff",
        "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages",
        "Access-Control-Allow-Headers": "Authorization, Content-Type"
    },
    "rels": {
        "https://api.w.org/": [
            "https://microsub-dev.jackjamieson.net/wp-json/"
        ]
    }
}
```

**Comment by jackjamieson2** [comment]
(As an aside, note that the auth-update branch is now unfunctional as a microsub server - my thought is that I can use this to figure out the auth problem and then implement a fix back in the dev branch)

**Comment by dshanske** [comment]
There is a lot of cruft in here from the Microsub endpoint. I think I need to trim it down.

**Comment by dshanske** [comment]
I think I had best branch from the last commit before the auth merge and do some work there

**Comment by jackjamieson2** [comment]
Sure thing, that should be the most recent commit to the dev
branch 31b0e11292d285ccfab4aa7965cbe409e4b61fd5

Thank you!!

**Comment by dshanske** [comment]
When I looked at your merge, it included a lot of Micropub stuff you don't need and I think that might be confusing the issue.

**Comment by dshanske** [comment]
I will give you a branch in my fork to follow once I set it up

**Comment by dshanske** [comment]
I have this fixed in early tests. Implementing scope checks, missing from the original version. This is with the Indieauth plugin only. Will add in the second piece later.

**Comment by jackjamieson2** [comment]
Hooray!! Very excited to have this resolved!

**Comment by dshanske** [comment]
I'm working on the PR so that the endpoint is to spec. The PR will include a rework on the endpoint class and related auth functions. I'm reworking the scope handling as well. In Micropub, scope is checked before anything else, switching to that model.

**Comment by jackjamieson2** [comment]
Per discussion at: 
1. https://chat.indieweb.org/wordpress/2019-04-23#t1556037624927800
2. https://chat.indieweb.org/dev/2019-04-23#t1556037932319500

It turns out this was not a bug with Yarns per se, but rather an issue with my server configuration. It was corrected by adding the following to my .htaccess: `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

This means, this issue can be closed :)
