### ISSUE TITLE
RSS feeds - HTML escaped

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#60]
When previewing HTML feeds in Yarns admin UI, HTML markup is escaped, so displays as text.

**Comment by jackjamieson2** [comment]
As far as I can tell, this occurs because Parse-This uses `htmlspecialchars()` on HTML content for RSS feeds. 

see https://github.com/dshanske/parse-this/blob/master/includes/class-parse-this-rss.php#L79

```
'content'     => array_filter(
	array(
		'html' => htmlspecialchars( $item->get_content( true ) ),
		'text' => wp_strip_all_tags( $item->get_content( true ) ),
	)
),
```

As far as I can tell, skipping htmlspecialchars works fine here (at least in Yarns' use case).

@dshanske - Is it feasible to remove the call to `htmlspecialchars()` in Parse-This?  If not, then I can decode this field in Yarns after it has been returned by Parse-This.

**Comment by jackjamieson2** [comment]
I added a branch to my fork in case it's a useful reference: https://github.com/jackjamieson2/parse-this/tree/rss_parsing

**Comment by dshanske** [comment]
I am suggesting that I remove the special characters and replace with a kses function

**Comment by jackjamieson2** [comment]
Fixed as of https://github.com/dshanske/parse-this/commit/b5a628de097019eebf8520092997f118d08da618
