### ISSUE TITLE
Review endpoint changes 

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#64]
I've already merged @dshanske's pull request https://github.com/jackjamieson2/yarns-microsub-server/pull/63 to the dev branch

There are a few things to review:
- Some endpoint actions have optional parameters - (e.g. 'before' and 'after' on the 'timeline' action).  Currently optional parameters throw an error if empty, so need to add checking there.

- Some POST requests seem to be throwing errors (e.g. marking timeline items as read).  

Will note any additional issues here if I find them, and will resolve as soon as possible

**Comment by dshanske** [comment]
Yes, I didn't add any error checking. I have some ideas on that. Since you are now using input, you can add a function for each task inside the endpoint class and call it to keep things neat and readable

**Comment by jackjamieson2** [comment]
Looks like I was wrong about mark_read and mark_unread causing errors.  Might just be do to alltogethernow.io getting a new IP today

**Comment by jackjamieson2** [comment]
That's a good idea @dshanske, I was just looking at your nice clean code structure and thinking how to keep things that organized

**Comment by dshanske** [comment]
Learned from painful experience and continual wrong tries

**Comment by jackjamieson2** [comment]
I'm still on the path of continual wrong tries, but picking up a few tricks along the way

**Comment by jackjamieson2** [comment]
Had a bit of time to test things out a bit more today:

Looking pretty good, overall. I have merged dev back into the master branch.  Still a few things to work out but the updated endpoint (#63) and improved UI (#57) are a solid improvement.  

That said, there are some areas for further improvment:

Resurfaced errors
--
- I am once again getting error messages when marking posts read/unread in together (see #42)
- I am once again unable to see my channels in indigenous (see #8)

For both cases, I'll review the previous issues and try to resolve them.

Further improvements
--
- implement better error checking on endpoint actions.  Need to get a bit of dedicated time to think through a good method.

- it takes too long to respond to search queries (i.e. finding feeds on a site given a URL to query).  Seems that searching can take up to 25 seconds.  Alltogether.io times out after 10 seconds, so searches should be faster than that.

**Comment by dshanske** [comment]
Re the responses, look at https://developer.wordpress.org/reference/functions/rest_ensure_response/

**Comment by jackjamieson2** [comment]
Thanks, turns out the response issue (At least for Indigenous) was that content-type needs to be set explicitly to application/json - Done in 1b6ffad3eea768458558f8ba9ebe0fb896b1b3db

**Comment by dshanske** [comment]
You can do it as an argument to the constructor as well if you want

**Comment by jackjamieson2** [comment]
Update:

In the course of preparing [v0.1.6-beta](https://github.com/jackjamieson2/yarns-microsub-server/tree/v0.1.6-beta), I added simple handling of optional 'before' and 'after' parameters when responding to timeline requests.  This seems to be pretty stable. That said, I need to do another pass to decide if/what other validation is necessary

**Comment by jackjamieson2** [comment]
Implemented some validation in https://github.com/jackjamieson2/yarns-microsub-server/commit/1a7715df4cb052bf99f70cb4e80fd269870d9505

I think this should cover it, thought open to comments if I've missed anything important
