### ISSUE TITLE
Leftover files

### ISSUE THREAD

**Issue by jackjamieson2** [jackjamieson2/yarns-microsub-server#76]
When I first created this plugin, I adapted it from WordPress Webmention, using that as a template to build from.  As a result, I have a bunch of files I'm not using (`/bin/`, `gruntfile.js` etc.). 

I'd intended to adapt those files, but haven't done so yet.  Either I should remove them, or actually use them.

**Comment by dshanske** [comment]
#84 Addresses some of these.

**Comment by dshanske** [comment]
This was addressed.
