### ISSUE TITLE
IndieWeb Post Kinds Plugin Required

### ISSUE THREAD

**Issue by cjwillcock** [jackjamieson2/yarns-microsub-server#86]
Similar to #85, the IndieWeb Post Kinds plugin is required.

Adding a new follow to a channel does not work and does not provide any feedback to the user if the plugin is missing.

The documentation indicates it is optional.

**Comment by jackjamieson2** [comment]
Thanks,

Yarns *should* work without Post Kinds. In this case, both Yarns and Post Kinds use the same library for parsing (Parse-This).  There were some changes to Parse-This a few weeks ago, and I guess I made an error updating Yarns back then. I'll check it out

**Comment by jackjamieson2** [comment]
That should address the problem - I'm going to test it more thoroughly tomorrow.  

Careless mistake on my part! - @dshanske made some changes to Parse-This on June 30. I updated Yarns to accommodate those changes, but it looks like I didn't push those changes to the release. Dropped the ball between the hubbub of IndieWeb Summit and some travel right after.

**Comment by cjwillcock** [comment]
Thank you @jackjamieson2!
