### ISSUE TITLE
Adding urlencoded feed url results in empty feeds

### ISSUE THREAD

**Issue by bekoli** [jackjamieson2/yarns-microsub-server#94]
Affect YarnsMicrosubServer version: 1.0.2
Affected Wordpress version: 5.2.3

Adding a feed formatted with urlencoded parameters like `%3A` results in invalid feed urls. 

Example

Input: `xs=32%3AsA` 
Result: `xs=32sA`
Expected: `xs=32:sA`

Consider using the appropriate urldecode() in PHP or decodeURI() / decodeURIComponent() in JS on adding new feeds.

Decoding URLs manually before adding them to a channel works.

**Comment by jackjamieson2** [comment]
Nice catch, I'll try to take care of this and some other small changes this week
